"use client"
import { usePathname } from 'next/navigation'
import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar/Navbar'
import clsx from "clsx"
import AuthContext from './context/AuthContext'
import ToastContext from './context/ToasterContext'
import {
  QueryClient,
  QueryClientProvider,
} from '@tanstack/react-query'
import useGetUser from './hooks/use-get-user'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const pathname = usePathname(); 
  // Create a client
  const queryClient = new QueryClient()

  return (
  <html lang="en">
    <body className={clsx(inter.className, 'text-dark-gray font-medium flex flex-col min-h-screen w-full ', )}>
      <AuthContext>
        <QueryClientProvider client={queryClient}>
          <ToastContext />
          {
            !pathname?.includes('auth') && (
              <Navbar /> 
            )
          }
          {children}
        </QueryClientProvider>
      </AuthContext>
    </body>
  </html>
  )
}
